import json
import os
import shutil
import random
from pathlib import Path
from collections import defaultdict

COCO_JSON      = "contamination_segment_clean.json"
IMAGES_SRC_DIR = "raw_photos"         
OUTPUT_DIR     = "yolo_dataset"
TRAIN_RATIO    = 0.8        
RANDOM_SEED    = 42


def coco_to_yolo_seg(json_path: str, output_dir: str,
                     images_src: str = "", train_ratio: float = 0.8,
                     seed: int = 42):

    with open(json_path, "r") as f:
        coco = json.load(f)

    categories = sorted(coco["categories"], key=lambda x: x["id"])
    cat_id_to_yolo = {cat["id"]: idx for idx, cat in enumerate(categories)}
    cat_names      = [cat["name"] for cat in categories]

    print("=== КАТЕГОРИ MAPPING ===")
    for cat in categories:
        print(f"  COCO id={cat['id']} '{cat['name']}' → YOLO class {cat_id_to_yolo[cat['id']]}")

    images = {img["id"]: img for img in coco["images"]}

    img_annotations = defaultdict(list)
    skipped = 0
    for ann in coco["annotations"]:
        if not ann.get("segmentation"):
            skipped += 1
            continue
        img_annotations[ann["image_id"]].append(ann)

    print(f"\nАлгасагдсан annotation (segmentation байхгүй): {skipped}")

    all_img_ids = list(images.keys())
    random.seed(seed)
    random.shuffle(all_img_ids)

    split_idx  = int(len(all_img_ids) * train_ratio)
    train_ids  = set(all_img_ids[:split_idx])
    val_ids    = set(all_img_ids[split_idx:])

    print(f"\n=== DATASET ХУВААЛТ ===")
    print(f"  Train: {len(train_ids)} зураг")
    print(f"  Val:   {len(val_ids)} зураг")

    out = Path(output_dir)
    for split in ["train", "val"]:
        (out / "images" / split).mkdir(parents=True, exist_ok=True)
        (out / "labels" / split).mkdir(parents=True, exist_ok=True)

    stats = {"train": {"images": 0, "labels": 0, "anns": 0},
             "val":   {"images": 0, "labels": 0, "anns": 0}}
    empty_label_count = 0

    for img_id, img_info in images.items():
        split = "train" if img_id in train_ids else "val"

        W = img_info["width"]
        H = img_info["height"]
        file_name = img_info["file_name"]
        stem = Path(file_name).stem

        anns = img_annotations.get(img_id, [])
        lines = []

        for ann in anns:
            yolo_class = cat_id_to_yolo[ann["category_id"]]

            for seg in ann["segmentation"]:
                coords = seg
                if len(coords) < 6:  
                    continue

                norm_coords = []
                for i in range(0, len(coords), 2):
                    x = coords[i]     / W
                    y = coords[i + 1] / H

                    x = max(0.0, min(1.0, x))
                    y = max(0.0, min(1.0, y))
                    norm_coords.extend([f"{x:.6f}", f"{y:.6f}"])

                line = f"{yolo_class} " + " ".join(norm_coords)
                lines.append(line)

        label_path = out / "labels" / split / f"{stem}.txt"
        with open(label_path, "w") as f:
            f.write("\n".join(lines))

        if not lines:
            empty_label_count += 1

        stats[split]["images"] += 1
        stats[split]["labels"] += 1
        stats[split]["anns"]   += len(lines)

        if images_src:
            src_path = Path(images_src) / file_name
            if src_path.exists():
                dst_path = out / "images" / split / Path(file_name).name
                shutil.copy2(src_path, dst_path)

    yaml_content = f"""# YOLOv8 Segmentation - Solar Panel Contamination Detection
# Auto-generated by coco_to_yolo_seg.py

path: {str(out.absolute())}
train: images/train
val: images/val

nc: {len(cat_names)}
names: {cat_names}
"""
    with open(out / "data.yaml", "w") as f:
        f.write(yaml_content)
    return out


if __name__ == "__main__":
    import sys

    json_file = sys.argv[1] if len(sys.argv) > 1 else COCO_JSON
    out_dir   = sys.argv[2] if len(sys.argv) > 2 else OUTPUT_DIR
    img_src   = sys.argv[3] if len(sys.argv) > 3 else IMAGES_SRC_DIR

    coco_to_yolo_seg(
        json_path   = json_file,
        output_dir  = out_dir,
        images_src  = img_src,
        train_ratio = TRAIN_RATIO,
        seed        = RANDOM_SEED,
    )